<?php
return [
    'zoom_level'           => 13,
    'detail_zoom_level'    => 20,
    'map_center_latitude'  => env('MAP_CENTER_LATITUDE', '-0.05530656473030525'),
    'map_center_longitude' => env('MAP_CENTER_LONGITUDE', '109.34951352010654'),
    // UNTUK MENGAMBIL LATITUDE DAN LONGITUDE SILAHKAN LAKUKAN SECARA MANUAL ATAU AKSES HALAMAN CREATE KEMUDIAN
    // GESER KE LOKASI YANG DI INGINKAN, GANTI KOORDINAT YANG DIINGINKAN YAKNI PONTIANAK
];
